** Read Later
*** Use SDKMan
#+begin_src bash
sdk list
sdk list java
sdk install leiningen
sdk install java 8.0.275.hs-adpt
sdk default java 8.0.275.hs-adpt
#+end_src

*** Use nvm
- https://github.com/coreybutler/nvm-windows
- https://github.com/nvm-sh/nvm
#+begin_src bash
nvm install 10.10.0
nvm list
nvm list available
#+end_src

*** add User to Docker User Group
#+begin_src powershell
([adsi]"WinNT://./Hyper-V Administrators,group").Add("WinNT://BASFAD/wangh151,user")
([adsi]"WinNT://./docker-users,group").Add("WinNT://BASFAD/wangh151,user")
([adsi]"WinNT://./Hyper-V Administrators,group").Add("WinNT://$env:UserDomain/$env:Username,user")
#+end_src

*** docker run Postgres
#+begin_src bash
docker pull timescale/timescaledb:latest-pg11
docker pull dpage/pgadmin4
docker run --name my_postgres -e POSTGRES_PASSWORD=flyway123 -e POSTGRES_USER=flyway -e POSTGRES_DB=rts_local -p 5432:5432 -d timescale/timescaledb:latest-pg11
docker run -d -p 5433:80 --name pgadmin4 -e PGADMIN_DEFAULT_EMAIL=test@123.com -e PGADMIN_DEFAULT_PASSWORD=123456 dpage/pgadmin4
#+end_src

*** npm init for Azure DevOps
#+begin_src bash
nvm install 12.20.0
npm config list
npm config set proxy=http://clientproxy.basf.net:8080
npm install -g vsts-npm-auth
vsts-npm-auth -config .npmrc
npm install @angular/cli -g
npm install increase-memory-limit -g
项目路径下执行：increase-memory-limiyt

vsts login --token h7qg7ffropkpmtvbcbz575bgfoabaanmxu4iuedm7kezrflsdyfa
vsts configure --defaults instance=https://dev.azure.com/basf4dev project=TechHero
#+end_src

*** Windows Terminal Key Bindins
- Close pane: crtl+shift+w
- Move pane focus: crtl+[direction arrow]
- Resize a pane: alt+shift+[direction arrow]
- Split a pane horizontal: alt+shift+-
- Split a pane vertical: alt+shift+plus

*** Docker context
on your local machine 
docker context create digpro --docker host=ssh://admdigpro@digproVM01.cad.basf.net

After adding the context you can use your local docker to check the container on digpro by adding the context to a command
docker -c digpro ps
docker --context digpro ps

You could switch the context, then all commands are executed on the remote machine
docker context use digpro

*** copy file in Docker
#+begin_src bash
docker cp colimo-proxy:/app/conf/nginx.conf .
docker cp rest_session.lua colimo-proxy:/app/lua/rest_session.lua
#+end_src

*** VSCode cannot attach remote container
Message: Command in container failed: (dd iflag=fullblock bs=8192 count=6055 2>/dev/null; dd iflag=fullblock bs=2264 count=1 2>/dev/null) | tar
delete cache: C:\Users\wangh154\AppData\Local\Temp\vsch\serverCache

*** get cookie 'token' by JS
#+begin_src javascript
document.cookie.match(`[;\s+]?token=([^;]*)`).pop()
#+end_src

*** parse JWT by JS
#+begin_src javascript
JSON.parse(window.atob(token.split(".")[1]))
#+end_src

*** IP Range of Azure Services
- [[https://docs.microsoft.com/en-us/power-platform/admin/online-requirements#ip-addresses-required][Power Platform URLs and IP address ranges]]
- [[https://www.microsoft.com/download/details.aspx?id=56519][Azure IP Ranges and Service Tags C Public Cloud]]
- [[https://www.microsoft.com/download/details.aspx?id=57062][Azure IP Ranges and Service Tags C China Cloud]]

*** Windows show proxy settings
C:\> netsh winhttp show proxy
PS C:\> Get-ItemProperty -Path "Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"
C:\> reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings"

** Certificates and Proxy
*** Import CA Certificates in JAVA key store
#+begin_src cmd
.\keytool.exe -importcert -file "BASF Root CA 21.cer" -keystore ..\jre\lib\security\cacerts -alias "BASFROOTCA"
.\keytool.exe -importcert -file "BASF Root CA 21.cer" -keystore C:\Users\wangh154\AppData\Roaming\JetBrains\IntelliJIdea2020.3\ssl\cacerts -alias "BASFROOTCA"
#+end_src

*** Terraform error: x509 certificate signed by unknown authority terraform
ca-certificates path: /etc/ssl/certs/ca-certificates.crt
ls -lR /etc/ssl
#+begin_src bash
apt-get install ca-certificates \
&& update-ca-certificates
#+end_src

*** Import CA root certificates on Linux System(Debian/Ubuntu)
- [[https://thomas-leister.de/en/how-to-import-ca-root-certificate/][How to import CA root certificates on Linux and Windows]]
- 1. use openssl to download cert at first.
- 2. extract only the root cert and import.
- 3. it seems certificates in cer, crt, pem are all the same. Only need to change the filename extension.
#+begin_src bash
openssl s_client -showcerts -servername server -connect basf.net:443 > basf-cacert.pem
sudo -i cp /workspaces/workspace2/basf-root-ca-cert.pem /usr/local/share/ca-certificates/extra/basf-root-ca-cert.crt
sudo -i update-ca-certificates
#+end_src

*** Certificate verification failed when using Azure CLI to deploy function app
error msg:
#+begin_src bash
eval $PROXYHK az functionapp deployment source config-zip -g cpshop_prod_rg  -n cpshop-prod-functions  --src bcp-functions-1642558598227.zip
Getting scm site credentials for zip deployment
Starting zip deployment. This operation can take a while to complete ...
HTTPSConnectionPool(host='cpshop-prod-functions.scm.chinacloudsites.cn', port=443): Max retries exceeded with url: /api/zipdeploy?isAsync=true (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Certificate verification failed. This typically happens when using Azure CLI behind a proxy that intercepts traffic with a self-signed certificate. Please add this certificate to the trusted CA bundle. More info: https://docs.microsoft.com/cli/azure/use-cli-effectively#work-behind-a-proxy.
#+end_src

Use the Azure CLI successfully:
- https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively?tabs=bash%2Cbash2#work-behind-a-proxy

import certificate:
- https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#work-behind-a-proxy
- https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate
#+begin_src bash
cat /workspaces/workspace2/deploy/certificates/basf-root-ca-cert.pem >> /opt/az/lib/python3.6/site-packages/certifi/cacert.pem
#+end_src

** Git
git log --pretty=oneline
git diff HEAD^^ HEAD^

- delete remote branch
git push origin --delete [branchname]
- delete local branch
git branch -d [branchname]
- prune cached remote branch
git fetch --prune origin

*** Git conflicts after squash merge
1. dev merge to master using squash
2. add new commits on dev
3. conflicts when dev merge to master again
- [[https://stackoverflow.com/questions/55113672/git-conflicts-after-squash-merge][Git conflicts after squash merge]]
- [[https://softwareengineering.stackexchange.com/questions/365658/does-squashing-pull-requests-break-gits-merging-algorithm][Does squashing pull requests break git's merging algorithm?]]

** Bash
- Generate Random Password
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1
- view system versoin
cat /etc/os-release

dpkg -S `which restydoc`

Ctrl + r (bck-i-search)

** kubectl
*** Get pod in Running
kubectl get pod -o wide -n bcp-site --field-selector=status.phase=Running
*** delete Evicted pod
kubectl get pods -n bcp-site | grep Evicted | awk '{print $1}' | xargs kubectl delete pod -n bcp-site

*** restart pod in kubectl
- https://segmentfault.com/a/1190000020675199
kubectl get pod {podname} -n {namespace} -o yaml | kubectl replace --force -f -
eval $PROXYHK kubectl get pod kb-sp-saml2 -n bcp-sso -o yaml | eval $PROXYHK  kubectl replace --force -f -

*** kubectl cluster level commands
#+begin_src bash
kubectl config get-contexts
kubectl config current-context
kubectl config use-context docker-desktop
kubectl top node
kubectl api-resources
kubectl cluster-info
#+end_src

*** kubectl resources level command
#+begin_src bash
kubectl get event -n <NAMESPACE> | grep <DEPLOYMENT_NAME>

kubectl port-forward <POD_NAME> <LOCALHOST_PORT>:<POD_PORT>
kubectl port-forward svc/<SERVICE_NAME> <LOCALHOST_PORT>:<SERVICE_PORT>
kubectl port-forward nginx-hht64 5000:80
kubectl port-forward svc/nginx 5000:80

kubectl logs <POD_NAME> -c <CONTAINER_NAME> -n <NAMESPACE>

# test if the account can do certain action
kubectl --as=system:serviceaccount:<NAMESPACE>:<SERVICE_ACCOUNT_NAME> auth can-i get configmap/<CONFIGMAP_NAME>
kubectl -n <NAMESPACE> auth can-i list secrets --as <USERACCOUNT>

kubectl top pod -n <NAMESPACE>

# Create ingress resource from a command line:
# Here is an ingress created with name ‘demo’ and class ‘nginx’ 
# and configured to use host “demo.localdev.me” to point to ‘demo’ service on port 80.
kubectl create ingress demo --class=nginx --rule="demo.localdev.me/*=demo:80"

# Copy secret from a namespace to another
kubectl get secret aks-ingress-tls --namespace=dev -o yaml | sed 's/namespace: .*/namespace: demo/' | kubectl apply -f -

# Open a bash or sh terminal inside a pod
kubectl exec -it <POD_NAME> -n <NAMESPACE> -- /bin/bash
kubectl exec -it <POD_NAME> -n <NAMESPACE> -- /bin/sh

# Copy files from/to a pod
kubectl cp <FILENAME> <NAMESPACE>/<PODNAME>:</path/to/file>
kubectl cp <NAMESPACE>/<PODNAME>:</path/to/file> <FILENAME>
kubectl cp file.txt default/nginx-345gjig:/home
kubectl cp default/nginx-345gjig:/home/file.txt ./file.txt

# Apply resources directly through terminal
$echo "
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  selector:
    env: metrics
  type: ClusterIP
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
" | kubectl apply -f -
#+end_src

** PowerShell
*** Set HOMEPATH instead of Z:
ls env:
$env:HOMEDRIVE="C:"
$env:HOMEPATH="\Users\wangh154\"

*** view and set System Environment Variable
#+begin_src powershell
[System.Environment]::GetEnvironmentVariable("PATH","user")
[System.Environment]::GetEnvironmentVariable("PATH","machine")
[System.Environment]::SetEnvironmentVariable("HTTP_PROXY ", "http://webproxy-hk-failover.global.basf.net:8080", [System.EnvironmentVariableTarget]::User)
[System.Environment]::SetEnvironmentVariable("HTTPS_PROXY ", "http://webproxy-hk-failover.global.basf.net:8080", [System.EnvironmentVariableTarget]::User)
#+end_src

** cURL
*** curl SSL certificates
- curl SSL certificates: https://curl.se/docs/sslcerts.html

curl --location --request --insecure GET 'https://basf-ec-coatings-kb-test.chinaeast2.cloudapp.chinacloudapi.cn/auth/get_sso.cgi' \
--header 'Cookie:  mellon-cookie=5ae018959c61c2e8d1274f1c776f17f1;'

curl -s -LI URL -o /dev/null -w '%{http_code}'
-L
Tells cURL to follow the URL if it is marked as having been moved

-I
Only returns the HTTP header, which is where the HTTP response code is located

-s
Causes cURL to run in silent mode. Ordinarily, cURL displays a progress meter as it executes.

-o
Tells cURL where to write the general output of the command. In this case, /dev/null, the Linux and macOS bit bucket is used. On Windows systems, you can write to a file named nul, for which Windows provides built-in device driver support.

-w
Specifies what cURL should write to standard output, and how to format that information. The string '%{http_code}' simply writes the contents of the variable http_code

** SQL Server

*** Page query in SQL Server
#+begin_src sql
SELECT * from [table_name] order by [id] offset 2 row fetch next 5 row only;
#+end_src

** Power Platform

*** Output CSV in UTF-8 format in Power Automate
If your .csv file shows broken characters instead of Chinese, 
it is because the encoded file does not include BOM for UTF-8. 
So, please add 3 BOM characters as below. It will show the text normally in excel.
#+begin_src javascript
concat(uriComponentToString('%EF%BB%BF'),body('Create_CSV_table'))
#+end_src
- https://powerusers.microsoft.com/t5/General-Power-Automate/Convert-exvel-to-CSV-UTF-8/td-p/472040
Flow Actions: OneDrive for Business C Update File C YouTube
- https://365community.online/flow-actions-onedrive-for-business-update-file-youtube
